### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by trasherdk** [SChernykh/p2pool#17]
Trying to build on `Slackware 14.2 (x64)` box failed.

I had to patch `CMakeLists.txt` to accept the cmake version installed.

```diff
-if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.6.0") 
+if (${CMAKE_VERSION} VERSION_GREATER "3.5.1") 
```

And I ended up with this:

```sh
[ 61%] Building CXX object CMakeFiles/p2pool.dir/src/block_cache.cpp.o
In file included from /.../p2pool/src/common.h:282:0,
                 from /.../p2pool/src/block_cache.cpp:18:
/.../p2pool/src/util.h:125:13: error: specialization of ‘template<class _Tp> struct std::hash’ in different namespace [-fpermissive]
 struct std::hash<p2pool::hash>
             ^
In file included from /usr/include/c++/5.5.0/bits/basic_string.h:5574:0,
                 from /usr/include/c++/5.5.0/string:52,
                 from /usr/include/c++/5.5.0/stdexcept:39,
                 from /usr/include/c++/5.5.0/array:38,
                 from /usr/include/c++/5.5.0/tuple:39,
                 from /usr/include/c++/5.5.0/functional:55,
                 from /.../p2pool/src/common.h:41,
                 from /.../p2pool/src/block_cache.cpp:18:
/usr/include/c++/5.5.0/bits/functional_hash.h:58:12: error:   from definition of ‘template<class _Tp> struct std::hash’ [-fpermissive]
     struct hash;
            ^
CMakeFiles/p2pool.dir/build.make:182: recipe for target 'CMakeFiles/p2pool.dir/src/block_cache.cpp.o' failed
make[2]: *** [CMakeFiles/p2pool.dir/src/block_cache.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/p2pool.dir/all' failed
make[1]: *** [CMakeFiles/p2pool.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SChernykh** [comment]
GCC 5.5.0 is a really old compiler, you should update it. That said, I've submitted a possible fix in 3aa270a072cbd517b01754bc4ab677dd8370114d
The cmake version shouldn't be a problem, that line in CMakeLists.txt will just ignore older versions.

**Comment by trasherdk** [comment]
`gcc 5.5.0` is what comes in a stable Slackware 14.2, so unless I want to maintain another version package, that's it :)

The cmake patch is necessary for `cmake 3.5.2` again, that's what I got. Without it, `cmake ../p2pool` complains, and exit.

```sh
CMake Error at CMakeLists.txt:8 (if):
  if given arguments:

    "3.5.2" "VERSION_GREATER_EQUAL" "3.6.0"

  Unknown arguments specified
```

Seems 3aa270a did the trick, compiler-wise.  
Now I am missing the `gss` thingy.  
Is this [GNU Generic Security Service Library](https://ftp.gnu.org/gnu/gss/) the thing? Or is there another, better suited source, for this?

```sh
[100%] Linking CXX executable p2pool
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../x86_64-slackware-linux/bin/ld: cannot find -lgss
```

**Comment by SChernykh** [comment]
You can try to remove -lgss to see if you really need it. Not all distros require it for p2pool.

**Comment by trasherdk** [comment]
Cool :smile: 
```sh
[100%] Linking CXX executable p2pool
[100%] Built target p2pool
```
Looks good
```sh
$ ldd p2pool 
        linux-vdso.so.1 (0x00007ffc9c396000)
        libzmq.so.5 => /usr/lib64/libzmq.so.5 (0x00007f364adf3000)
        libuv.so.1 => /usr/lib64/libuv.so.1 (0x00007f364abc4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f364a9a7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f364a7a3000)
        libsodium.so.23 => /usr/lib64/libsodium.so.23 (0x00007f364a54c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f364a243000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3649e7a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f364b074000)
        libunwind.so.8 => /usr/lib64/libunwind.so.8 (0x00007f3649c60000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3649a58000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f36496dc000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f36494c5000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f36492ab000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f3649086000)
```

**Comment by trasherdk** [comment]
Thanks.
